{{- if eq (include "object-storage-mn.enabled" .) "true" -}}
apiVersion: v1
kind: Secret
metadata:
  name: eric-data-object-storage-mn-secret
  labels:
    chart: {{ .Chart.Name }}
    release: {{ .Release.Name }}
type: Opaque
data:
  accesskey: {{ "accesskey01" | b64enc | quote }}
  secretkey: {{ "secretkey01" | b64enc | quote }}
{{- end}}