apiVersion: v1
kind: ConfigMap
metadata:
  creationTimestamp: null
  name: custom-collector-config
data:
  config.properties: |-
    edca.kafka.topic=pm-data
    edca.kafka.bootstrapUrl=eric-oss-dmaap-kafka.edca-sprint2:9092
    edca.bdr.host=eric-data-object-storage-mn.edca-sprint2
    edca.bdr.port=9000
    edca.bdr.bucket=pm-data
    edca.bdr.accesskey=ccuser
    edca.bdr.secretkey=ccuser123
    edca.catalog.host=edca-sprint2.hoff135.rnd.gic.ericsson.se
    edca.catalog.port=80
    edca.test.endpointInterface=MINIO
    edca.test.metadataFile=test-data/pm-data/metadata.json
    edca.test.dataFile=test-data/pm-data/data.json
    edca.test.sftpPath=testsftp/testsftp.txt
    edca.test.counter=2
    edca.sftp.host=141.137.237.213
    edca.sftp.port=22
    edca.sftp.user=drguser
    edca.sftp.password=Test@123
---
apiVersion: v1
kind: Pod
metadata:
  creationTimestamp: null
  labels:
    run: custom-collector
  name: custom-collector
spec:
  containers:
  - image: armdocker.rnd.ericsson.se/proj-edca-dev/custom-collector:1.0.11
    name: custom-collector
    command:
    - sh
    - -c
    - --
    args:
    - while true;do sleep 30;done
    resources:
      requests:
        memory: "250Mi"
        cpu: "125m"
      limits:
        memory: "500Mi"
        cpu: "250m"
    volumeMounts:
    - name: cc
      mountPath: "/app/configuration"
  volumes:
  - name: cc
    configMap:
      name: custom-collector-config
  dnsPolicy: ClusterFirst
  restartPolicy: Always
status: {}