# This is a YAML-formatted file.
# Declare variables to be passed into your templates.
productInfo:
  rstate: R1A01

replicaCount: 1

fullnameOverride:

global:
  registry:
    url: armdocker.rnd.ericsson.se
  timezone: UTC

updateStrategy:
 type: RollingUpdate
 rollingUpdate:
   maxSurge: 1
   maxUnavailable: 0

imageCredentials:
  registry:
    url: armdocker.rnd.ericsson.se
  repoPath: proj-edca-dev
  pullPolicy: IfNotPresent

images:
  drg-simulator:
    name: drg-image
    tag: 1.0.4

drg:
  interactive: true
  kafka:
    sasl.jaas.config: "org.apache.kafka.common.security.plain.PlainLoginModule required username=\"admin\" password=\"admin_secret\";"
    sasl.mechanism: "PLAIN"
    security.protocol: "SASL_PLAINTEXT"
  catalog:
    url: <catalog_Url>
  minio:
    accesskey: <access_key>
    secretkey: <secret_key>


resources:
  drg:
    requests:
      ephemeral-storage: 5Gi
      memory: 512Mi
      cpu: 500m
    limits:
      ephemeral-storage: 15Gi
      memory: 1Gi
      cpu: 1

