
# Default values for eric-edca-drg-simulator.
# This is a YAML-formatted file.
# Declare variables to be passed into your templates.

global:
  timezone: UTC
  registry:
    url: armdocker.rnd.ericsson.se
    # Secret must be manually created in the namespace, no default value
    # pullSecret: eric-adp-example-secret

productInfo:
  # R-State of the product. R State should match helm chart version (3.1.0 -> R2A)
  # To automate it when packaging the helm chart rstate can be generated
  # and below value replaced with correct R-Statei by e.g. Bob
  rstate: RSTATE

updateStrategy:
 type: RollingUpdate
 rollingUpdate:
   maxSurge: 1
   maxUnavailable: 0

imageCredentials:
  # repoPath include the image path relative to the registry url, excluding image name
  # repoPath: sandbox/adp-staging/adp-cicd
  #pullPolicy: IfNotPresent
  pullPolicy: IfNotPresent
  repoPath: REPO_PATH
  registry:
  # overrides global registry url
  # url: armdocker.companyA.se
  #- Secret must be manually created in the namespace, no default value
  # pullSecret: REPO_SECRET

images:
  chassis:
    name: IMAGE_NAME
    tag: VERSION

replicaCount: 1

nameOverride: ""
fullnameOverride: ""

service:
  type: ClusterIP
  port: 8080    # Changed from 80 to 8080 and spring application is hosted on 8080

ingress:
  enabled: false
  annotations:
    ericsson.com/product-name: "Microservice Chassis"
    ericsson.com/product-number: "CXP90001/2"
    ericsson.com/product-revision: "{{ .Values.productInfo.rstate }}"

  hosts:
    - host: chart-example.local
      paths: []

  tls: []
  #  - secretName: chart-example-tls
  #    hosts:
  #      - chart-example.local
eric-pm-server:
  rbac:
    appMonitoring:
      enabled: true

prometheus:
  path: /actuator/prometheus
  scrape: true

resources:
  requests:
    memory: 512Mi
    cpu: 250m
  limits:
    memory: 2Gi
    cpu: 500m

nodeSelector: {}

tolerations: []

affinity: {}
