# This is a YAML-formatted file.
# Declare variables to be passed into your templates.
productInfo:
  rstate: R1A01

replicaCount: 1

fullnameOverride:

global:
  registry:
    url: armdocker.rnd.ericsson.se
  timezone: UTC

updateStrategy:
 type: RollingUpdate
 rollingUpdate:
   maxSurge: 1
   maxUnavailable: 0

imageCredentials:
  repoPath: proj-edca-catalog-service
  pullPolicy: IfNotPresent
  
images:
  catalog-service:
    name: eric-edca-catalog
    tag: VERSION
  #pgInitContainer:
  #  name: eric-data-document-database-pg
  #  tag: latest
  #  repoPath: proj-edca-db
  #  pullPolicy: IfNotPresent
  
container:
  ports:
    http: 8080
    #notification: 9002    

service:
  type: ClusterIP
  port: 8080
  #notificationport: 9002

ingress:
  enabled: true
  annotations:

  hosts:
    - host: edca.hoff135.rnd.gic.ericsson.se
      paths: []

  tls: []
  #  - secretName: chart-example-tls
  #    hosts:
  #      - chart-example.local

resources:
  catalog:
    requests:
      ephemeral-storage: 5Gi
      memory: 512Mi
      cpu: 500m
    limits:
      ephemeral-storage: 15Gi
      memory: 2Gi
      cpu: 2
  
#oss:
#  secretName:

#persistentVolumeClaim:
#  enabled: true
#  storageClassName: "-"
#  accessMode: ReadWriteOnce
#  size: 20Gi
#  mountPath: /edca-ext

dbServiceName: eric-data-document-database-pg
#initContainerName: edca-db-connection
#credentials:
#  kubernetesSecretName: eric-eo-evnfm-vm-secret-pg
#  keyForUserId: custom-user
#  keyForUserPw: custom-pwd
#  keyForSuperPw: super-pwd
#  keyForMetricsPw: metrics-pwd
#  keyForReplicaId: replica-user
#  keyForReplicaPw: replica-pwd

edcaDBSchema:
  postgresdatabase:
    schema: adp_gs
    port: 5432

#  edcadatabase:
#    schema: edcacatalog
#    port: 5432


#initContainerParams:
#  startupwait: 5

#Prometheus params for Performance Monitoring.
#prometheus:
#  path: "/vnflcm/metrics"
#  scrape: "true"
